spring.application.name=backend-shop
#spring.liquibase.change-log=classpath:/db/master.xml
#spring.liquibase.contexts=dev
#spring.jpa.hibernate.ddl-auto=none
spring.liquibase.enabled=false

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:test
spring.datasource.username=admin
spring.datasource.password=
